from typing import Any as __Any, overload as __overload
 
######################################## SPECIALS ELEMENTS ########################################
   
class Type:
    class Boolean:
        def __init__(self, name: str, value : 'bool|Type.Boolean'): ...
        def __eq__(self, other : 'bool|Type.Boolean') -> 'Type.Boolean': ... # pyright: ignore[reportIncompatibleMethodOverride]

    class Number:
        def __init__(self, name: str, value : 'float|Type.Number'): ...
        def __gt__(self, other : 'float|Type.Number') -> 'Type.Boolean': ... 
        def __lt__(self, other : 'float|Type.Number') -> 'Type.Boolean': ...
        def __ge__(self, other : 'float|Type.Number') -> 'Type.Boolean': ...
        def __le__(self, other : 'float|Type.Number') -> 'Type.Boolean': ...
        def __eq__(self, other : 'float|Type.Number') -> 'Type.Boolean': ... # pyright: ignore[reportIncompatibleMethodOverride]

    class Composite:
        def __init__(self, name: str, value : 'dict|Type.Composite'): ...
        @__overload
        def get(self, type: 'Type.Boolean', channel: 'Type.Number') -> 'Type.Boolean': ... # pyright: ignore[reportNoOverloadImplementation]
        @__overload
        def get(self, type: 'Type.Number', channel: 'Type.Number') -> 'Type.Number': ...

    class Video:
        def __init__(self, name: str, value : '__Any|Type.Video'): ...

    class Audio:
        def __init__(self, name: str, value : '__Any|Type.Audio'): ...
        
    type Any = 'Type.Boolean | Type.Number | Type.Composite | Type.Video | Type.Audio'

class Import:
    class Boolean(Type.Boolean):
        def __init__(self, name: str, description: str): ...
        def __call__(self) -> Type.Boolean: ...

    class Number(Type.Number):
        def __init__(self, name: str, description: str): ...
        def __call__(self) -> Type.Number: ...
        
    class Composite(Type.Composite):
        def __init__(self, name: str, description: str): ...
        def __call__(self) -> Type.Composite: ...

    class Video(Type.Video):
        def __init__(self, name: str, description: str): ...
        def __call__(self) -> Type.Video: ...
    
    class Audio(Type.Audio):
        def __init__(self, name: str, description: str): ...
        def __call__(self) -> Type.Audio: ...

class Export:
    def __init__(self, name: str, description: str): ...
    
    @__overload
    def __call__(self,value : Type.Boolean) -> None: ... # pyright: ignore[reportNoOverloadImplementation]
    @__overload
    def __call__(self,value : Type.Number) -> None: ...
    @__overload
    def __call__(self,value : Type.Composite) -> None: ...
    @__overload
    def __call__(self,value : Type.Video) -> None: ...
    @__overload
    def __call__(self,value : Type.Audio) -> None: ...
    

########################################### COMPONENTS ############################################

class MemoryRegister:
    """
    Memory register to store a value across ticks.
    
    Args:
        initial_value (float): The initial value of the memory register. Must be a constant number.
    """
    def __init__(self, value: float): ...
    def __call__(self) -> 'MemoryRegister': ...
    def set(self, value : Type.Number): ...
    def reset(self): ...
    @property
    def value(self) -> Type.Number: ...
