import { CompilerContext } from './compiler-context';
import { BLOCK_IDS } from './sw-mapping';
import { InputNumber, InputBoolean, OutputBoolean } from '../std/io';
import { ConstantNumberBlock } from '../std/constants';

export class Compiler {
    public static compile(name: string): string {
        const components = CompilerContext.getInstance().getComponents();
        
        let nodesXml = '';
        let logicXml = '';

        components.forEach((comp) => {
            const typeId = BLOCK_IDS[comp.typeName as keyof typeof BLOCK_IDS];

            // 1. GESTION DES NODES (I/O Extérieurs)
            if (comp instanceof InputNumber || comp instanceof InputBoolean || comp instanceof OutputBoolean) {
                const type = comp.typeName.includes('number') ? '1' : '0'; // 0=Bool, 1=Number
                const mode = comp instanceof OutputBoolean ? '1' : '0';    // 0=Input, 1=Output
                
                nodesXml += `
        <n id="${comp.id}" name="${(comp as any).name}" type="${type}" mode="${mode}">
            <p x="${comp.position.x}" y="${comp.position.y}"/>
        </n>`;
            } 
            
            // 2. GESTION DE LA LOGIQUE INTERNE
            else {
                logicXml += `
        <c id="${comp.id}" type="${typeId}">
            <p x="${comp.position.x}" y="${comp.position.y}"/>`;

                // Gestion des constantes
                if (comp instanceof ConstantNumberBlock) {
                    logicXml += `\n            <v v="${comp.value}"/>`;
                }

                // Gestion des entrées (Wiring)
                // On inspecte dynamiquement les propriétés qui sont des Signaux
                Object.keys(comp).forEach(key => {
                    const val = (comp as any)[key];
                    if (val && val.sourceBlockId !== undefined) {
                        // Stormworks utilise <i index="0" component_id="ID"/> pour les entrées
                        // L'index dépend du bloc (ex: GreaterThan: 0=A, 1=B)
                        const inputIndex = key === 'a' ? 0 : 1; 
                        logicXml += `\n            <i index="${inputIndex}" component_id="${val.sourceBlockId}"/>`;
                    }
                });

                logicXml += `\n        </c>`;
            }
        });

        return `<?xml version="1.0" encoding="UTF-8"?>
<microprocessor name="${name}" description="Generated by TypeScript Compiler" width="2" height="2">
    <nodes>${nodesXml}
    </nodes>
    <components>${logicXml}
    </components>
</microprocessor>`;
    }
}